exports.CompositorsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Compositor List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>Período</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].periodo}</td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Editar</a>][<a href="/compositores/delete/${slist[i].id}">Apagar</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.CompositorFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Data Obito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>

                    
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/alunos">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                    <legend>Metadata</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                    <label>Biografia</label>
                    <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                    <label>Data Nascimento</label>
                    <input class="w3-input w3-round" type="date" name="dataNasc" value="${a.dataNasc}"/>
                    <label>Data Obito</label>
                    <input class="w3-input w3-round" type="date" name="dataObito" value="${a.dataObito}"/>
                    <label>Período</label>
                    <input class="w3-input w3-round" type="text" name="periodo" value="${a.periodo}"/>
                </fieldset>
                    
                
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.CompositorPage = function( comp, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Aluno: ${comp.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${comp.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>ID: </b> ${comp.id}</li>    
                    <li><b>Nome: </b> ${comp.nome}</li>
                    <li><b>Biografia: </b>${comp.bio}</li>
                    <li><b>Data Nascimento: </b>${comp.dataNasc}</li>
                    <li><b>Data Obito: </b>${comp.dataObito}</li>
                    <li><b>Período: </b>${comp.periodo}</li>
                </ul>
            </div> `
            //<div class="w3-container w3-margin-8">
            //    <ul class="w3-ul">
            //`
            //for(let i=1; i < 9; i++){
            //    key = `tpc${i}`
            //    if(key in aluno){
            //        pagHTML += `
            //            <li><b>TPC${i}</b></li>
            //        `
            //    }
            //}
    

    pagHTML +=     `</ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}